/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'IconAkarIcons:envelope': typeof import('~icons/akar-icons/envelope')['default']
    'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    'IconAkarIcons:linkedinv2Fill': typeof import('~icons/akar-icons/linkedinv2-fill')['default']
    'IconIconamoon:linkedin': typeof import('~icons/iconamoon/linkedin')['default']
    'IconIconamoon:menuBurgerHorizontal': typeof import('~icons/iconamoon/menu-burger-horizontal')['default']
    'IconIon:socialLinkedinOutline': typeof import('~icons/ion/social-linkedin-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
